name: Crypto Radar V5

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TARGET_CHAT_ID: ${{ secrets.TARGET_CHAT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python "bot - Kopya.py"
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Run Crypto Radar V5
        run: python bot-v5Kopya.py
